[package]
name = "nrdev-rs"
version = "0.1.0"
edition = "2021"
description = "Professional website for NRDev to engage with new clients"

[dependencies]
rocket = "0.5.0-rc.2"

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.2"
features = ["tera"]
